detect:  # 检测哪些内容来判断
  move-rotation: true  # 视角移动
  move-position: false  # 水平位置移动（可能误判）
  chat: false  # 发送聊天
  command: true  # 发送指令
  mouse-click: true  # 鼠标点击

move-sensitivity: 2  # 水平位移的灵敏度（防止误判）

afk-check-interval: 300  # AFK检测间隔（秒）
afk-placeholder: "&8&o&o[AFK]"  # %isAFK%占位符显示内容
afk-god-mode: false  # 玩家AFK时是否无敌

packet-blacklist:
  - SOUND_EFFECT
  - PARTICLE
  - BLOCK_ACTION
  - MAP_DATA
  - BLOCK_CHANGE
  - UPDATE_LIGHT
  - ENTITY_METADATA
  - ENTITY_VELOCITY
  - ENTITY_TELEPORT
  - SCOREBOARD_OBJECTIVE
  - UPDATE_SCORE
  - ENTITY_RELATIVE_MOVE
  - ENTITY_HEAD_LOOK
  - ENTITY_RELATIVE_MOVE_AND_ROTATION
  - ENTITY_ROTATION
  - ENTITY_POSITION_SYNC
  # - MULTI_BLOCK_CHANGE

message:
  afk-self: "<yellow>你挂机了。"
  afk-broadcast: "<gray>%player% 挂机了。"
  back-self: "<green>欢迎回来！"
  back-broadcast: "<gray>%player% 回来了。"
  afk-reload: "<green>插件已成功重载."