name: afk
version: ${version}
authors: ["Tacocat-i", "Stabrinai"]
main: com.github.stabrinai.afkplugin.afk
api-version: '1.21'
folia-supported: true
softdepend: [PlaceholderAPI]
depend: [packetevents]